version: 2

project_name: schema-tool

before:
  hooks:
    - go mod tidy

builds:
  - id: schema-tool
    main: ./cmd/schema-tool
    binary: schema-tool
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: bootcs-cn
    name: boocs-schema
  draft: false
  prerelease: auto
